# Generated by Django 5.2.3 on 2025-08-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=50)),
                ('problem_type', models.CharField(choices=[('math', 'Mathematics'), ('dsa', 'Data Structures & Algorithms')], default='math', max_length=10)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='problems/images/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='problems/pdfs/')),
                ('input_format', models.TextField(blank=True, help_text='Description of input format')),
                ('output_format', models.TextField(blank=True, help_text='Description of output format')),
                ('constraints', models.TextField(blank=True, help_text='Constraints for the problem')),
                ('sample_input', models.TextField(blank=True)),
                ('sample_output', models.TextField(blank=True)),
                ('time_limit', models.IntegerField(default=5, help_text='Time limit in seconds')),
                ('memory_limit', models.CharField(default='128m', help_text='Memory limit (e.g., 128m, 256m)', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_attempts', models.IntegerField(default=0)),
                ('successful_completions', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(help_text='Input for this test case')),
                ('expected_output', models.TextField(help_text='Expected output for this test case')),
                ('is_sample', models.BooleanField(default=False, help_text='Whether this is a sample test case')),
                ('is_hidden', models.BooleanField(default=True, help_text='Whether this test case is hidden from users')),
                ('points', models.IntegerField(default=1, help_text='Points awarded for passing this test case')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
