# Generated by Django 5.2.3 on 2025-08-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_accepted_submissions_user_avatar_user_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contest_rating',
            field=models.IntegerField(blank=True, help_text='Rating from contests (null if no contests participated)', null=True),
        ),
    ]
