# Generated by Django 5.2.3 on 2025-08-02 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_contest_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contest_rating',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_contest_time',
        ),
    ]
