# Generated by Django 5.2.3 on 2025-08-02 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('JUDGING', 'Judging'), ('ACCEPTED', 'Accepted'), ('WRONG_ANSWER', 'Wrong Answer'), ('TIME_LIMIT_EXCEEDED', 'Time Limit Exceeded'), ('MEMORY_LIMIT_EXCEEDED', 'Memory Limit Exceeded'), ('RUNTIME_ERROR', 'Runtime Error'), ('COMPILATION_ERROR', 'Compilation Error'), ('ERROR', 'System Error')], max_length=50)),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('memory_used', models.BigIntegerField(blank=True, null=True)),
                ('actual_output', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('language', models.CharField(choices=[('cpp', 'C++'), ('py', 'Python'), ('java', 'Java')], max_length=50)),
                ('input_data', models.TextField(blank=True, null=True)),
                ('total_test_cases', models.IntegerField(default=0)),
                ('passed_test_cases', models.IntegerField(default=0)),
                ('score', models.FloatField(default=0.0, help_text='Score based on passed test cases')),
                ('max_execution_time', models.FloatField(blank=True, null=True)),
                ('max_memory_used', models.BigIntegerField(blank=True, help_text='Memory in bytes', null=True)),
                ('output_data', models.TextField(blank=True, null=True)),
                ('error_data', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('JUDGING', 'Judging'), ('ACCEPTED', 'Accepted'), ('WRONG_ANSWER', 'Wrong Answer'), ('TIME_LIMIT_EXCEEDED', 'Time Limit Exceeded'), ('MEMORY_LIMIT_EXCEEDED', 'Memory Limit Exceeded'), ('RUNTIME_ERROR', 'Runtime Error'), ('COMPILATION_ERROR', 'Compilation Error'), ('ERROR', 'System Error')], default='PENDING', max_length=50)),
                ('execution_time', models.FloatField(blank=True, help_text='Execution time in seconds', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problem')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
