# Generated by Django 5.2.3 on 2025-08-02 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(max_length=500)),
                ('option_d', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1)),
                ('explanation', models.TextField()),
                ('sequence_order', models.IntegerField()),
                ('difficulty_level', models.CharField(default='medium', max_length=20)),
                ('hint_text', models.TextField(blank=True, help_text='Hint to guide learner thinking')),
            ],
            options={
                'ordering': ['sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='MCQSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('total_questions', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='MCQResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1)),
                ('is_correct', models.BooleanField()),
                ('time_taken_seconds', models.IntegerField(help_text='Time taken to answer in seconds')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('learning_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_sessions.learningsession')),
                ('mcq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcq_generation.mcq')),
            ],
        ),
    ]
