# Generated by Django 5.2.3 on 2025-08-02 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mcq_generation', '0001_initial'),
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mcqresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mcqset',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problem'),
        ),
        migrations.AddField(
            model_name='mcq',
            name='mcq_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='mcq_generation.mcqset'),
        ),
        migrations.AlterUniqueTogether(
            name='mcqresponse',
            unique_together={('user', 'mcq', 'learning_session')},
        ),
        migrations.AlterUniqueTogether(
            name='mcq',
            unique_together={('mcq_set', 'sequence_order')},
        ),
    ]
