# Generated by Django 5.2.3 on 2025-08-02 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning_sessions', '0001_initial'),
        ('mcq_generation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsession',
            name='mcq_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mcq_generation.mcqset'),
        ),
    ]
